// <auto-generated />
using System;
using Fuel_Tracking_application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelTrackingapplication.Migrations
{
    [DbContext(typeof(FuelDbContext))]
    [Migration("20230119155054_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fuel_Tracking_application.Models.Domain.Fuel", b =>
                {
                    b.Property<Guid>("dataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("filled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("filledVolume")
                        .HasColumnType("int");

                    b.Property<int>("fuelPrice")
                        .HasColumnType("int");

                    b.Property<int>("odometerTotal")
                        .HasColumnType("int");

                    b.Property<string>("reportingEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dataId");

                    b.ToTable("FuelData");
                });
#pragma warning restore 612, 618
        }
    }
}
